CREATE TABLE `version_one` (

	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`unique_key`	INTEGER,
	`rec_status`	TEXT,
	`global_record_id`	TEXT,
	`first_save_logon_name`	TEXT,
	`first_save_time`	TEXT,
	`last_save_logon_name`	TEXT,
	`last_save_time`	TEXT,
	
	`partner`	TEXT,
	`county`	TEXT,
	`client_name`	TEXT,
	`age`	TEXT,
	`gender`	TEXT,
	`occupation`	TEXT,
	`occupation_other`	TEXT,
	`sub_county`	TEXT,
	
	`test_location`	TEXT,
	`first_positive_sub_county`	TEXT,
	`first_positive_hf`	TEXT,
	`first_positive_ward`	TEXT,
	`confirmation_county`	TEXT,
	`confirmation_hf`	TEXT,
	`referred_county`	TEXT,
	`referred_hf`	TEXT,
	`referred_expected_linkage_date`	TEXT,
	`first_positive_county_fac`	TEXT,
	`first_positive_county_comm`	TEXT,
	`first_positive_date`	TEXT,
	`confirmation_date`	TEXT,
	`first_positive_hf_mfl`	TEXT,
	`confirmation_hf_mfl`	TEXT,
	`referred_hf_mfl`	TEXT,

	`follow_up_1`	TEXT,
	`follow_up_1_date`	TEXT,
	`follow_up_1_reached`	TEXT,
	`follow_up_1_fail_reason`	TEXT,
	`follow_up_1_fail_reason_other`	TEXT,
	`follow_up_2`	TEXT,
	`follow_up_2_date`	TEXT,
	`follow_up_2_reached`	TEXT,
	`follow_up_2_fail_reason`	TEXT,
	`follow_up_2_fail_reason_other`	TEXT,

	`linked`	TEXT,
	`linked_date`	TEXT,
	`linked_county`	TEXT,
	`linked_hf`	TEXT,
	`ccc_number`	TEXT,
	`linked_comments`	TEXT,
	`linked_reason`	TEXT,
	`linked_reason_other`	TEXT,
	`linked_hf_mfl`	TEXT

);

